# Generated by Django 6.0.3 on 2026-03-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_recuperar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Empleado'), (3, 'Cliente')], default=3, verbose_name='Tipo'),
        ),
    ]
