# Generated by Django 6.0.3 on 2026-06-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0004_alter_usuario_correo_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, unique=True, verbose_name='Contraseña'),
        ),
    ]
