# Generated by Django 6.0.2 on 2026-03-26 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentaApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
