# Generated by Django 6.0.3 on 2026-03-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentaApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Ventas'},
        ),
    ]
