# Generated by Django 6.0.3 on 2026-03-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentaApp', '0005_alter_venta_options_alter_venta_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Ventas'},
        ),
    ]
