# Generated by Django 6.0.3 on 2026-03-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoletaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cantidad_boletos',
            field=models.IntegerField(verbose_name='Cantidad de Boletos'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='precio_boleta',
            field=models.IntegerField(verbose_name='Precio de Boleta'),
        ),
    ]
