# Generated by Django 6.0.3 on 2026-03-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoletaApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boleta',
        ),
    ]
