# Generated by Django 6.0.3 on 2026-06-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoletaApp', '0002_alter_boleta_cantidad_boletos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cantidad_boletos',
            field=models.PositiveBigIntegerField(verbose_name='Cantidad de Boletos'),
        ),
    ]
