# Generated by Django 6.0.3 on 2026-06-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoletaApp', '0003_alter_boleta_cantidad_boletos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cantidad_boletos',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Boletos'),
        ),
    ]
