# Generated by Django 6.0.3 on 2026-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('precio_boleta', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='EventoApp')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
            },
        ),
    ]
