# Generated by Django 6.0.3 on 2026-03-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventoApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
