# Generated by Django 6.0.3 on 2026-03-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventoApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='precio_boleta',
            field=models.IntegerField(verbose_name='Precio de Boleta'),
        ),
    ]
