# Generated by Django 6.0.3 on 2026-03-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventoApp', '0004_alter_evento_hora_inicio_alter_evento_precio_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidad_maxima',
            field=models.IntegerField(verbose_name='Capacidad Máxima'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
