# Generated by Django 6.0.3 on 2026-06-18 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventoApp', '0005_alter_evento_capacidad_maxima_alter_evento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidad_maxima',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Capacidad Máxima'),
        ),
    ]
