# Generated by Django 6.0.3 on 2026-06-18 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventoApp', '0006_alter_evento_capacidad_maxima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidad_maxima',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Capacidad Máxima'),
        ),
    ]
