# Generated by Django 6.0.3 on 2026-03-29 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservacionApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='cantidad_mesas',
            field=models.IntegerField(verbose_name='Cantidad de Mesas'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='cantidad_personas',
            field=models.IntegerField(verbose_name='Cantidad de Personas'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_reservacion',
            field=models.DateField(verbose_name='Fecha de Reservación'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='ocasion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocasión'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
