# Generated by Django 6.0.3 on 2026-03-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('licor', 'Licor'), ('cerveza', 'Cerveza'), ('cigarrillo', 'Cigarrillo')], max_length=20)),
                ('cantidad_MD', models.IntegerField(blank=True, null=True)),
                ('unidad_MD', models.CharField(blank=True, choices=[('ml', 'Ml'), ('l', 'L'), ('paquete', 'Paquete'), ('medio', 'Medio')], max_length=8, null=True)),
                ('stock', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='ProductoApp')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
