# Generated by Django 6.0.3 on 2026-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_MD',
            field=models.CharField(blank=True, choices=[('ml', 'Ml'), ('l', 'Litros'), ('paquete', 'Paquete'), ('medio', 'Medio')], max_length=8, null=True),
        ),
    ]
