# Generated by Django 6.0.3 on 2026-03-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoApp', '0002_alter_producto_unidad_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_MD',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ProductoApp'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('licor', 'Licor'), ('cerveza', 'Cerveza'), ('cigarrillo', 'Cigarrillo')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_MD',
            field=models.CharField(choices=[('ml', 'Ml'), ('l', 'Litros'), ('paquete', 'Paquete'), ('medio', 'Medio')], max_length=8, verbose_name='Unidad de Medida'),
        ),
    ]
