# Generated by Django 6.0.3 on 2026-03-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoApp', '0003_alter_producto_cantidad_md_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_MD',
            field=models.CharField(blank=True, choices=[('ml', 'Ml'), ('l', 'Litros'), ('paquete', 'Paquete'), ('medio', 'Medio')], max_length=8, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
