# Generated by Django 6.0.3 on 2026-06-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductoApp', '0004_alter_producto_unidad_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.IntegerField(verbose_name='Precio Unitario'),
        ),
    ]
