# Generated by Django 6.0.3 on 2026-03-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detalle_VentaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='cant_prod',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='created',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_unit',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='updated',
        ),
    ]
