# Generated by Django 6.0.3 on 2026-03-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detalle_VentaApp', '0002_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
