# Generated by Django 6.0.2 on 2026-03-26 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Detalle_VentaApp', '0003_delete_detalleventa'),
        ('ProductoApp', '0002_alter_producto_unidad_md'),
        ('VentaApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_prod', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductoApp.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentaApp.venta')),
            ],
            options={
                'verbose_name': 'detalle venta',
                'verbose_name_plural': 'detalles de ventas',
            },
        ),
    ]
