# Generated by Django 6.0.3 on 2026-03-26 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detalle_VentaApp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='stock',
        ),
    ]
