# Generated by Django 6.0.3 on 2026-03-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detalle_VentaApp', '0005_remove_detalleventa_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='created',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='total',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='updated',
        ),
    ]
