# Generated by Django 6.0.3 on 2026-03-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detalle_VentaApp', '0006_remove_detalleventa_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cant_prod',
            field=models.IntegerField(verbose_name='Cantidad de Producto'),
        ),
    ]
