# Generated by Django 6.0.3 on 2026-06-18 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detalle_VentaApp', '0007_alter_detalleventa_cant_prod'),
        ('VentaApp', '0006_alter_venta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentaApp.venta', verbose_name='Venta'),
        ),
    ]
